function up(knex) {
  return knex.raw(`
      ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;
      ALTER TABLE friendship ENABLE ROW LEVEL SECURITY;
      ALTER TABLE friend_request ENABLE ROW LEVEL SECURITY;
      ALTER TABLE post ENABLE ROW LEVEL SECURITY;
      ALTER TABLE comment ENABLE ROW LEVEL SECURITY;
      ALTER TABLE reaction ENABLE ROW LEVEL SECURITY;
  `);
}

function down(knex) {
  return knex.raw(`
      ALTER TABLE "user" DISABLE ROW LEVEL SECURITY;
      ALTER TABLE friendship DISABLE ROW LEVEL SECURITY;
      ALTER TABLE friend_request DISABLE ROW LEVEL SECURITY;
      ALTER TABLE post DISABLE ROW LEVEL SECURITY;
      ALTER TABLE comment DISABLE ROW LEVEL SECURITY;
      ALTER TABLE reaction DISABLE ROW LEVEL SECURITY;
  `);
}

export { up, down };
